# Use the official Golang image as the base image
FROM golang:alpine

# Install necessary packages including air
RUN apk add --no-cache git && \
    go install github.com/air-verse/air@latest

# Set the working directory
WORKDIR /app

# Copy the Go modules manifests
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the application code
COPY . .

# Run tidy
RUN go mod tidy

# Expose the port on which the application runs
EXPOSE 4000

# Command to run Air for live reload
CMD ["air", "-c", ".air.toml"]